/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.7 */
/* Sun Feb 27 15:51:06 2022 */

/* parameterized module instance */
pll_xclk_base __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), 
    .LOCK( ));
