//Verilog instantiation template

pcie_subsys _inst (.pcie_x1_top_bus_num(), .pcie_x1_top_cmd_reg_out(), .pcie_x1_top_dev_cntl_out(), 
            .pcie_x1_top_dev_num(), .pcie_x1_top_func_num(), .pcie_x1_top_lnk_cntl_out(), 
            .pcie_x1_top_mm_enable(), .pcie_x1_top_msi(), .pcie_x1_top_npd_num_vc0(), 
            .pcie_x1_top_pd_num_vc0(), .pcie_x1_top_phy_ltssm_state(), .pcie_x1_top_pm_power_state(), 
            .pcie_x1_top_rx_bar_hit(), .pcie_x1_top_rx_data_vc0(), .pcie_x1_top_rx_lbk_data(), 
            .pcie_x1_top_rx_lbk_kcntl(), .pcie_x1_top_rxdp_dllp_val(), .pcie_x1_top_rxdp_pmd_type(), 
            .pcie_x1_top_rxdp_vsd_data(), .pcie_x1_top_sci_addr(), .pcie_x1_top_sci_rddata(), 
            .pcie_x1_top_sci_wrdata(), .pcie_x1_top_tx_ca_cpld_vc0(), .pcie_x1_top_tx_ca_cplh_vc0(), 
            .pcie_x1_top_tx_ca_npd_vc0(), .pcie_x1_top_tx_ca_nph_vc0(), 
            .pcie_x1_top_tx_ca_pd_vc0(), .pcie_x1_top_tx_ca_ph_vc0(), .pcie_x1_top_tx_data_vc0(), 
            .pcie_x1_top_tx_dllp_val(), .pcie_x1_top_tx_lbk_data(), .pcie_x1_top_tx_lbk_kcntl(), 
            .pcie_x1_top_tx_pmtype(), .pcie_x1_top_tx_vsd_data(), .pcie_x1_top_cmpln_tout(), 
            .pcie_x1_top_cmpltr_abort_np(), .pcie_x1_top_cmpltr_abort_p(), 
            .pcie_x1_top_dl_active(), .pcie_x1_top_dl_inactive(), .pcie_x1_top_dl_init(), 
            .pcie_x1_top_dl_up(), .pcie_x1_top_flip_lanes(), .pcie_x1_top_force_disable_scr(), 
            .pcie_x1_top_force_lsm_active(), .pcie_x1_top_force_phy_status(), 
            .pcie_x1_top_force_rec_ei(), .pcie_x1_top_hdinn0(), .pcie_x1_top_hdinp0(), 
            .pcie_x1_top_hdoutn0(), .pcie_x1_top_hdoutp0(), .pcie_x1_top_hl_disable_scr(), 
            .pcie_x1_top_hl_gto_cfg(), .pcie_x1_top_hl_gto_det(), .pcie_x1_top_hl_gto_dis(), 
            .pcie_x1_top_hl_gto_hrst(), .pcie_x1_top_hl_gto_l0stx(), .pcie_x1_top_hl_gto_l0stxfts(), 
            .pcie_x1_top_hl_gto_l1(), .pcie_x1_top_hl_gto_l2(), .pcie_x1_top_hl_gto_lbk(), 
            .pcie_x1_top_hl_gto_rcvry(), .pcie_x1_top_hl_snd_beacon(), .pcie_x1_top_inta_n(), 
            .pcie_x1_top_msi_enable(), .pcie_x1_top_no_pcie_train(), .pcie_x1_top_np_req_pend(), 
            .pcie_x1_top_npd_buf_status_vc0(), .pcie_x1_top_npd_processed_vc0(), 
            .pcie_x1_top_nph_buf_status_vc0(), .pcie_x1_top_nph_processed_vc0(), 
            .pcie_x1_top_pd_buf_status_vc0(), .pcie_x1_top_pd_processed_vc0(), 
            .pcie_x1_top_ph_buf_status_vc0(), .pcie_x1_top_ph_processed_vc0(), 
            .pcie_x1_top_phy_pol_compliance(), .pcie_x1_top_pll_refclki(), 
            .pcie_x1_top_pme_en(), .pcie_x1_top_pme_status(), .pcie_x1_top_rst_n(), 
            .pcie_x1_top_rx_end_vc0(), .pcie_x1_top_rx_malf_tlp_vc0(), .pcie_x1_top_rx_st_vc0(), 
            .pcie_x1_top_rx_us_req_vc0(), .pcie_x1_top_rxrefclk(), .pcie_x1_top_sci_en(), 
            .pcie_x1_top_sci_en_dual(), .pcie_x1_top_sci_int(), .pcie_x1_top_sci_rd(), 
            .pcie_x1_top_sci_sel(), .pcie_x1_top_sci_sel_dual(), .pcie_x1_top_sci_wrn(), 
            .pcie_x1_top_serdes_pdb(), .pcie_x1_top_serdes_rst_dual_c(), 
            .pcie_x1_top_sys_clk_125(), .pcie_x1_top_tx_ca_cpl_recheck_vc0(), 
            .pcie_x1_top_tx_ca_p_recheck_vc0(), .pcie_x1_top_tx_dllp_sent(), 
            .pcie_x1_top_tx_end_vc0(), .pcie_x1_top_tx_lbk_rdy(), .pcie_x1_top_tx_nlfy_vc0(), 
            .pcie_x1_top_tx_pwrup_c(), .pcie_x1_top_tx_rdy_vc0(), .pcie_x1_top_tx_req_vc0(), 
            .pcie_x1_top_tx_serdes_rst_c(), .pcie_x1_top_tx_st_vc0(), .pcie_x1_top_unexp_cmpln(), 
            .pcie_x1_top_ur_np_ext(), .pcie_x1_top_ur_p_ext(), .pcie_refclk_refclkn(), 
            .pcie_refclk_refclko(), .pcie_refclk_refclkp(), .pcie_mfx1_top_ix_dec_wb_cyc(), 
            .pcie_mfx1_top_ix_ipx_rx_data(), .pcie_mfx1_top_ix_ipx_tx_ca_cpld(), 
            .pcie_mfx1_top_ix_ipx_tx_ca_cplh(), .pcie_mfx1_top_ix_ipx_tx_ca_npd(), 
            .pcie_mfx1_top_ix_ipx_tx_ca_nph(), .pcie_mfx1_top_ix_ipx_tx_ca_pd(), 
            .pcie_mfx1_top_ix_ipx_tx_ca_ph(), .pcie_mfx1_top_ix_pci_int_req(), 
            .pcie_mfx1_top_ix_wbm_dat(), .pcie_mfx1_top_ix_wbs_adr(), .pcie_mfx1_top_ix_wbs_bte(), 
            .pcie_mfx1_top_ix_wbs_cti(), .pcie_mfx1_top_ix_wbs_cyc(), .pcie_mfx1_top_ix_wbs_dat(), 
            .pcie_mfx1_top_ix_wbs_sel(), .pcie_mfx1_top_ox_dec_adr(), .pcie_mfx1_top_ox_dec_bar_hit(), 
            .pcie_mfx1_top_ox_dec_func_hit(), .pcie_mfx1_top_ox_ipx_cc_npd_num(), 
            .pcie_mfx1_top_ox_ipx_cc_pd_num(), .pcie_mfx1_top_ox_ipx_tx_data(), 
            .pcie_mfx1_top_ox_sys_rst_func_n(), .pcie_mfx1_top_ox_wbm_adr(), 
            .pcie_mfx1_top_ox_wbm_bte(), .pcie_mfx1_top_ox_wbm_cti(), .pcie_mfx1_top_ox_wbm_cyc(), 
            .pcie_mfx1_top_ox_wbm_dat(), .pcie_mfx1_top_ox_wbm_sel(), .pcie_mfx1_top_ox_wbs_dat(), 
            .pcie_mfx1_top_ix_clk_125(), .pcie_mfx1_top_ix_ipx_dl_up(), 
            .pcie_mfx1_top_ix_ipx_malf_tlp(), .pcie_mfx1_top_ix_ipx_rx_end(), 
            .pcie_mfx1_top_ix_ipx_rx_st(), .pcie_mfx1_top_ix_ipx_tx_rdy(), 
            .pcie_mfx1_top_ix_rst_n(), .pcie_mfx1_top_ix_wbm_ack(), .pcie_mfx1_top_ix_wbs_stb(), 
            .pcie_mfx1_top_ix_wbs_we(), .pcie_mfx1_top_ox_ipx_cc_processed_npd(), 
            .pcie_mfx1_top_ox_ipx_cc_processed_nph(), .pcie_mfx1_top_ox_ipx_cc_processed_pd(), 
            .pcie_mfx1_top_ox_ipx_cc_processed_ph(), .pcie_mfx1_top_ox_ipx_tx_end(), 
            .pcie_mfx1_top_ox_ipx_tx_req(), .pcie_mfx1_top_ox_ipx_tx_st(), 
            .pcie_mfx1_top_ox_sys_rst_n(), .pcie_mfx1_top_ox_wbm_stb(), 
            .pcie_mfx1_top_ox_wbm_we(), .pcie_mfx1_top_ox_wbs_ack(), .pcie_mfx1_top_ox_wbs_err());